package carpark.carpark;

import java.util.HashMap;

/**
 * Manages an array with ParkingSpace objects
 */
public class Carpark {
    /**
     * HashMap containing the parking spot number and vehicle parked on it
     */
    protected static final HashMap<Integer, Car> spots = new HashMap<>();

    /**Private constructor of carpark class*/
    private Carpark(){

    }

    /**
     * Writes a vehicle and its parking spot into the spots HashMap upon parking
     * @param body Class generated by the entering vehicle
     */
    public static void enter(Body body) {
        Car car = body.generateCar();
        Carpark.spots.put(body.getParkingSpotNumber(), car);
        ServerData.setLastEntered(body);
    }

    /**
     * Deletes a vehicle and its parking spot from the spots HashMap upon leaving
     * @param body Class generated by the leaving vehicle
     * @return The exited vehicle
     */
    public static Car exit(Body body) {
        ServerData.setLastExited(body);
        return Carpark.spots.remove(body.getParkingSpotNumber());
    }

    /** @return Number of free parking spots */
    public static int getSpotsOccupied() {
        return spots.size();
    }
}